name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Give execute permission to gradlew
      run: chmod +x gradlew

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: List all project files
      run: |
        echo "=== Listing build output folders ==="
        find . -type d -name "outputs" || true
        echo "=== Listing all .apk files ==="
        find . -type f -name "*.apk" || true

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: APK
        path: |
          **/*.apk
